# Generated by Django 4.0.6 on 2025-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0002_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarks',
            name='Group',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
