# Generated by Django 4.0.6 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0004_document_signable_user_signed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signed_document',
            name='User',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
