# Generated by Django 4.0.6 on 2025-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0005_user_signed_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Birth',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Gps',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_House',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_ID',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Job',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Job_Address',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Job_Contact',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Landmark',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Street',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='visa_info',
            name='Garantor_Title',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
