# Generated by Django 4.0.6 on 2025-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0006_visa_info_garantor_birth_visa_info_garantor_gps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withness_Signed_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.IntegerField()),
                ('User', models.IntegerField()),
                ('Name', models.CharField(max_length=10000)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
