# Generated by Django 4.0.6 on 2025-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0007_withness_signed_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Contact', models.CharField(max_length=300)),
                ('Password', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=300)),
                ('Location', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Confirm_Signed_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signed', models.IntegerField()),
                ('User', models.IntegerField()),
                ('Client', models.IntegerField()),
                ('Time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
