# Generated by Django 4.0.6 on 2025-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0008_agent_account_confirm_signed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_info',
            name='Agent',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
