# Generated by Django 4.0.6 on 2025-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0009_visa_info_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Account_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.IntegerField()),
                ('User', models.IntegerField()),
                ('Status', models.CharField(max_length=300)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
