# Generated by Django 4.0.6 on 2025-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0010_agent_account_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
