# Generated by Django 4.0.6 on 2025-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0011_last_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Agent',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
