# Generated by Django 4.0.6 on 2025-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0012_booking_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_logs',
            name='Agent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
