# Generated by Django 4.0.6 on 2025-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0013_call_logs_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField()),
                ('Booking', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Count', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
