# Generated by Django 4.0.6 on 2025-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0014_preview_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_account',
            name='Link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
