# Generated by Django 4.0.6 on 2025-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0015_agent_account_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Form_Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField()),
                ('Client', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
                ('Status', models.CharField(max_length=300)),
                ('Transfared', models.CharField(max_length=300)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
