# Generated by Django 4.0.6 on 2025-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0016_agent_form_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_info',
            name='Agent_Type',
            field=models.CharField(default='Agent', max_length=300),
            preserve_default=False,
        ),
    ]
