# Generated by Django 4.0.6 on 2025-06-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0017_visa_info_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_form_funds',
            name='Completed',
            field=models.CharField(default='No', max_length=300),
            preserve_default=False,
        ),
    ]
