# Generated by Django 4.0.6 on 2025-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0018_agent_form_funds_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_account_link',
            name='Type',
            field=models.CharField(default='Agent', max_length=300),
            preserve_default=False,
        ),
    ]
