# Generated by Django 4.0.6 on 2025-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0019_agent_account_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_info',
            name='Agent',
            field=models.CharField(default='No', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator_info',
            name='Confirm_Agent',
            field=models.CharField(default='No', max_length=10000),
            preserve_default=False,
        ),
    ]
