# Generated by Django 4.0.6 on 2025-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0020_administrator_info_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator_info',
            name='Method',
            field=models.CharField(default='mtn-gh', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent_account',
            name='Method',
            field=models.CharField(default='mtn-gh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent_form_funds',
            name='Refrence',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
