# Generated by Django 4.0.6 on 2025-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0021_administrator_info_method_agent_account_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_menu',
            name='Sign',
            field=models.CharField(default='No', max_length=10000),
            preserve_default=False,
        ),
    ]
