# Generated by Django 4.0.6 on 2025-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0022_side_menu_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signed_document',
            name='Status',
            field=models.CharField(default='Pending', max_length=300),
            preserve_default=False,
        ),
    ]
