# Generated by Django 4.0.6 on 2025-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0023_user_signed_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_menu',
            name='Level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
