# Generated by Django 4.0.6 on 2025-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0024_side_menu_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signed_document',
            name='Uid',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
